language: php
  php:
    - "5.3"
    - "5.4"
    - "5.5"
    - "5.6"
    - "hhvm"

env:
  - DB=mysql

mysql:
  database: test
  username: root
  encoding: utf8

install:
  - mysql -e 'create database test;'
  - echo "USE mysql; UPDATE user SET password=PASSWORD('password') WHERE user='root'; FLUSH PRIVILEGES;" | mysql -u root

before_script:
  - phpenv config-rm xdebug.ini
